### PR TITLE
Fix comment typos

### PR DESCRIPTION
**Pull request by JKingsnorth**
Minor PR to fix a few typos in comments

### CODE REVIEW

**Comment by mike-potter** [comment]
We are no longer using these github projects due to the large number of submodules in Open Atrium.  So please submit this as a normal patch to the drupal.org issue queue for the oa_wiki module.

**Comment by JKingsnorth** [comment]
Ah, OK, thanks Mike.

**Comment by JKingsnorth** [comment]
Mike, I just noticed that all the oa_\* project pages still point back to github 'for the latest development version'. I guess those project descriptions will need updating.

**Comment by mike-potter** [comment]
Yep, we'll get rid of those references.

**Pull request closed without merging**
